name: Check xmtp-agent-examples
# Runs every hour
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch: # Keeps manual triggering option

jobs:
  run-agent:
    runs-on: ubuntu-latest

    steps: # sd
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clone XMTP agent examples
        run: |
          git clone https://github.com/ephemeraHQ/xmtp-agent-examples.git
          cd xmtp-agent-examples

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "yarn"
        env:
          SKIP_YARN_COREPACK_CHECK: "1"

      - name: Create .env file with secrets
        run: |
          cd xmtp-agent-examples
          echo "XMTP_ENV=${{ vars.XMTP_ENV }}" > .env
          echo "WALLET_KEY=${{ secrets.WALLET_KEY }}" >> .env
          echo "ENCRYPTION_KEY=${{ secrets.ENCRYPTION_KEY }}" >> .env

      - name: Install dependencies
        run: |
          cd xmtp-agent-examples
          yarn install

      - name: Run agent
        run: |
          cd xmtp-agent-examples
          timeout 60s yarn dev | tee output.log
          if grep -q "Waiting for messages..." output.log; then
            echo "Success: Agent started successfully and is waiting for messages"
            exit 0
          else
            echo "Error: Agent did not reach 'Waiting for messages...' state"
            exit 1
          fi
