name: TS_Gm
description: "should verify performance of the library in the dev network"

on:
  schedule:
    - cron: "15,45 * * * *" # Runs at 15 and 45 minutes past each hour
  workflow_dispatch:

jobs:
  TS_Gm:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [production]
    env:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      LOGGING_LEVEL: ${{ vars.LOGGING_LEVEL }}
      XMTP_ENV: ${{ matrix.environment }}
      GEOLOCATION: ${{ vars.GEOLOCATION }}
      GM_BOT_ADDRESS: ${{ vars.GM_BOT_ADDRESS }}
      WALLET_KEY: ${{ secrets.WALLET_KEY }}
      ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL || 'xmtp-qa' }}
    steps:
      - uses: actions/checkout@v4
      - name: Debug API key
        run: |
          if [ -n "${{ secrets.DATADOG_API_KEY }}" ]; then
            echo "API key is available in test job"
          else
            echo "API key is NOT available in test job"
          fi
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "yarn"
        env:
          SKIP_YARN_COREPACK_CHECK: "1"
      - run: corepack enable
      - run: yarn
      - name: Run tests with retry
        run: yarn cli test TS_Gm
      - name: Send Slack notification
        if: always()
        env:
          JOB_STATUS: ${{ job.status }}
        run: npx tsx helpers/slack.ts
      - name: Upload reports and snapshots artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ts_gm_${{ matrix.environment }}
          path: |
            logs/
            logs/**/*.png
