name: Package Manager Compatibility Test

on:
  push:
    branches: [main, master]
    paths:
      - "bots/gm-bot/**"
  pull_request:
    branches: [main, master]
    paths:
      - "bots/gm-bot/**"
  workflow_dispatch:

jobs:
  test-package-managers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install package managers
        run: |
          # Install via npm global (standard approach)
          npm install -g yarn
          npm install -g pnpm

          # Install bun
          curl -fsSL https://bun.sh/install | bash
          source ~/.bashrc

          # Verify installations directly
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)" 
          echo "Yarn version: $(yarn --version || echo 'Not available')"
          echo "PNPM version: $(pnpm --version || echo 'Not available')"
          echo "Bun version: $(bun --version || echo 'Not available')"

      - name: Examine packages.sh script
        run: |
          # Let's see how the script is checking for package managers
          if [ -f "./scripts/packages.sh" ]; then
            echo "First 30 lines of packages.sh:"
            head -n 30 ./scripts/packages.sh
            
            # Check how it's detecting package managers
            grep -n "pnpm" ./scripts/packages.sh
          else
            echo "packages.sh not found at expected location"
            find . -name "packages.sh" -type f
          fi

      - name: Fix permission and run tests
        run: |
          # Source bashrc to make bun available
          source ~/.bashrc

          # Print all available package managers and their locations
          echo "Available package managers:"
          npm -g list | head -n 10
          which npm
          which yarn
          which pnpm
          which bun

          # Create all possible symlinks to increase chances of detection
          sudo ln -sf $(which pnpm) /usr/local/bin/pnpm
          sudo ln -sf $(which pnpm) /usr/bin/pnpm

          # Try running the script
          chmod +x ./scripts/packages.sh
          ./scripts/packages.sh
