name: Package Manager Compatibility Test

on:
  push:
    branches: [main, master]
    paths:
      - "bots/gm-bot/**"
  pull_request:
    branches: [main, master]
    paths:
      - "bots/gm-bot/**"
  workflow_dispatch:

jobs:
  test-package-managers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install package managers
        run: |
          # Set shell explicitly for pnpm
          export SHELL=/bin/bash

          # Install required package managers
          npm install -g yarn
          npm install -g pnpm@latest
          curl -fsSL https://bun.sh/install | bash

          # Source bashrc to make bun available
          source ~/.bashrc

          # Determine paths
          NPM_GLOBAL_PATH="$(npm config get prefix)/bin"
          BUN_PATH="$HOME/.bun/bin"

          # Export paths to GITHUB_PATH
          echo "$NPM_GLOBAL_PATH" >> $GITHUB_PATH
          echo "$BUN_PATH" >> $GITHUB_PATH

          # Create pnpm directory manually instead of using pnpm setup
          mkdir -p "$HOME/.local/share/pnpm"
          echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH

          # Add symlink for pnpm
          ln -sf "$(which pnpm)" "$HOME/.local/share/pnpm/pnpm"

          # Add to current session PATH
          export PATH="$NPM_GLOBAL_PATH:$BUN_PATH:$HOME/.local/share/pnpm:$PATH"

          # Verify installations
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)" 
          echo "Yarn version: $(yarn --version)"
          echo "PNPM version: $(pnpm --version || echo 'Not available')"
          echo "Bun version: $(bun --version || echo 'Not available')"

      - name: Run package manager tests
        run: |
          # Source bashrc again to ensure all paths are available
          source ~/.bashrc

          # Verify package managers are available
          echo "Checking package managers:"
          which npm || echo "npm not found"
          which yarn || echo "yarn not found"
          which pnpm || echo "pnpm not found"
          which bun || echo "bun not found"

          # Run your test script
          chmod +x ./scripts/packages.sh
          ./scripts/packages.sh
        env:
          SHELL: /bin/bash
