name: Package Manager Compatibility Test

on:
  workflow_dispatch:
    # Optional inputs if you want to provide parameters when running manually
    inputs:
      reason:
        description: "Reason for running the test"
        required: false
        default: "Pre-merge verification"

jobs:
  test-package-managers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js with nvm
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run package manager tests
        run: |
          # Install required package managers
          npm install -g yarn pnpm
          curl -fsSL https://bun.sh/install | bash

          # Add bun to PATH
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

          # Enable corepack for yarn management
          corepack enable

          # Make the script executable and run it
          chmod +x ./scripts/packages.sh
          ./scripts/packages.sh
