name: Package Manager Compatibility Test

on:
  push:
    branches-ignore: [main]

jobs:
  test-package-managers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js with nvm
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run package manager tests
        run: |
          chmod +x ./scripts/packages.sh
          ./scripts/packages.sh
