name: Package Manager Compatibility Test

on:
  push:
    branches: [main, master]
    paths:
      - "bots/gm-bot/**"
  pull_request:
    branches: [main, master]
    paths:
      - "bots/gm-bot/**"
  workflow_dispatch:

jobs:
  test-package-managers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install NVM
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm --version

      - name: Install package managers
        run: |
          # Install required package managers
          npm install -g yarn
          npm install -g pnpm@latest
          curl -fsSL https://bun.sh/install | bash

          # Source bashrc to make bun available
          source ~/.bashrc

          # Add bun to PATH
          export BUN_PATH="$HOME/.bun/bin"
          echo "PATH=$BUN_PATH:$PATH" >> $GITHUB_ENV

          # Ensure global npm packages are in PATH
          export NPM_GLOBAL_PATH="$(npm config get prefix)/bin"
          echo "PATH=$NPM_GLOBAL_PATH:$PATH" >> $GITHUB_ENV

          # Verify installations
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "Yarn version: $(yarn --version)"
          echo "PNPM version: $(pnpm --version || echo 'Not available')"
          echo "Bun version: $(bun --version || echo 'Not available')"

          # Disable corepack initially (script will handle it)
          corepack disable

      - name: Run package manager tests
        run: |
          # Source bashrc to make bun available
          source ~/.bashrc

          # Source NVM
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

          # Add package managers to PATH
          export NPM_GLOBAL_PATH="$(npm config get prefix)/bin"
          export BUN_PATH="$HOME/.bun/bin"
          export PATH="$BUN_PATH:$NPM_GLOBAL_PATH:$PATH"

          # Verify package managers are available
          echo "Checking package managers:"
          which npm || echo "npm not found"
          which yarn || echo "yarn not found"
          which pnpm || echo "pnpm not found"
          which bun || echo "bun not found"

          # Install pnpm if not available
          if ! which pnpm; then
            echo "Installing pnpm again..."
            npm install -g pnpm@latest
          fi

          # Only proceed if all package managers are available
          if which npm && which yarn && which pnpm && which bun; then
            # Make the script executable and run it
            chmod +x ./scripts/packages.sh
            ./scripts/packages.sh
          else
            echo "Some package managers are missing. Cannot proceed."
            exit 1
          fi
