name: Package Manager Compatibility Test

on:
  push:
    branches: [main, master]
    paths:
      - "bots/gm-bot/**"
  pull_request:
    branches: [main, master]
    paths:
      - "bots/gm-bot/**"
  workflow_dispatch:

jobs:
  test-package-managers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js and NVM
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install NVM
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm --version

          # Install Node versions that will be used in the test script
          nvm install 20
          nvm install 21
          nvm install 22
          nvm install 23

      - name: Install package managers
        run: |
          # Install package managers globally
          npm install -g yarn
          npm install -g pnpm

          # Install bun
          curl -fsSL https://bun.sh/install | bash
          source ~/.bashrc

          # Create required directory structure
          mkdir -p bots/gm-bot
          touch bots/gm-bot/yarn.lock

          # Print installed package managers
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)" 
          echo "Yarn version: $(yarn --version)"
          echo "PNPM version: $(pnpm --version)"
          echo "Bun version: $(bun --version || echo 'Not available')"

      - name: Make package managers available in PATH
        run: |
          # Make sure all package managers are in system PATH
          sudo ln -sf $(which npm) /usr/local/bin/npm
          sudo ln -sf $(which yarn) /usr/local/bin/yarn
          sudo ln -sf $(which pnpm) /usr/local/bin/pnpm
          sudo ln -sf $(which bun 2>/dev/null || echo "") /usr/local/bin/bun

          # Verify they're accessible through PATH
          command -v npm
          command -v yarn
          command -v pnpm
          command -v bun

      - name: Run package manager tests
        run: |
          # Source necessary environment
          source ~/.bashrc
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

          # Modify the script to run in place
          sed -i 's|cd bots/gm-bot || exit 1|mkdir -p bots/gm-bot; cd bots/gm-bot || exit 1|' ./scripts/packages.sh

          # Make script executable
          chmod +x ./scripts/packages.sh

          # Run the test script
          ./scripts/packages.sh
