name: Railway integration

on:
  # Manual trigger only for testing
  workflow_dispatch:

jobs:
  railway-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Check Railway CLI version
        run: |
          echo "Railway CLI version:"
          railway --version
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Check Railway connection status
        run: |
          echo "Checking Railway status:"
          railway status
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Verify Railway environment
        run: |
          echo "Checking if we're on Railway:"
          railway run -s xmtp-qa-testing:us-west bash -c 'echo "RAILWAY_SERVICE_ID: $RAILWAY_SERVICE_ID"'
          railway run -s xmtp-qa-testing:us-west bash -c 'echo "RAILWAY_PROJECT_ID: $RAILWAY_PROJECT_ID"'
          railway run -s xmtp-qa-testing:us-west bash -c 'echo "HOSTNAME: $HOSTNAME"'
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Run performance test on Railway
        run: |
          echo "Running performance test on service:"
          railway run -s xmtp-qa-testing:us-west yarn ts_performance
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Print completion message
        run: echo "Railway test execution completed"
