name: Test Railway Integration

on:
  # Manual trigger only for testing
  workflow_dispatch:

jobs:
  test-railway:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Login to Railway
        run: railway login --token ${{ secrets.RAILWAY_PROJECT_TOKEN }}

      - name: Run performance tests on Railway
        run: railway run --service xmtp-qa-testing:us-west yarn ts_performance

      - name: Print completion message
        run: echo "Railway test execution completed"
