name: TS_Performance_Railway
description: "should verify performance of the library in the dev network"

on:
  schedule:
    - cron: "*/30 * * * *" # This cron expression means every 30 minutes
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      LOGGING_LEVEL: ${{ vars.LOGGING_LEVEL }}
      XMTP_ENV: ${{ vars.XMTP_ENV }}
      GEOLOCATION: ${{ vars.GEOLOCATION }}
      BATCH_SIZE: ${{ vars.BATCH_SIZE }}
      MAX_GROUP_SIZE: ${{ vars.MAX_GROUP_SIZE }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "yarn"
        env:
          SKIP_YARN_COREPACK_CHECK: "1"
      - run: corepack enable
      - run: yarn
      - name: Run tests with retry
        run: |
          for i in {1..3}; do
            echo "Attempt $i..."
            yarn test TS_Performance && break
            if [ $i -eq 3 ]; then
              echo "Test failed after 3 attempts."
              exit 1
            fi
            sleep 10
          done

  railway-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Install dependencies once
        run: yarn install

      - name: Create logs directory
        run: mkdir -p logs

      # US West Region Test
      - name: Run performance test on US West
        run: |
          echo "Running performance test on US West:"
          railway run -s xmtp-qa-testing:us-west yarn test ts_performance | tee logs/us-west-performance.log
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      # US East Region Test
      - name: Run performance test on US East
        run: |
          echo "Running performance test on US East:"
          railway run -s xmtp-qa-testing:us-east yarn test ts_performance | tee logs/us-east-performance.log
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      # Europe Region Test
      - name: Run performance test on Europe
        run: |
          echo "Running performance test on Europe:"
          railway run -s xmtp-qa-testing:europe yarn test ts_performance | tee logs/europe-performance.log
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      # Asia Region Test
      - name: Run performance test on Asia
        run: |
          echo "Running performance test on Asia:"
          railway run -s xmtp-qa-testing:asia yarn test ts_performance | tee logs/asia-performance.log
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Upload log files
        uses: actions/upload-artifact@v4
        with:
          name: performance-logs
          path: logs/

      - name: Print completion message
        run: echo "Railway test execution completed for all regions"
