name: Railway integration

on:
  # Manual trigger only for testing
  workflow_dispatch:

jobs:
  railway-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Create logs directory
        run: mkdir -p logs

      # US West Region Test
      - name: Run performance test on US West
        run: |
          echo "Running performance test on US West:"
          railway run -s xmtp-qa-testing:us-west yarn install
          railway run -s xmtp-qa-testing:us-west yarn ts_performance > logs/us-west-performance.log 2>&1
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      # US East Region Test
      - name: Run performance test on US East
        run: |
          echo "Running performance test on US East:"
          railway run -s xmtp-qa-testing:us-east yarn install
          railway run -s xmtp-qa-testing:us-east yarn ts_performance > logs/us-east-performance.log 2>&1
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      # Europe Region Test
      - name: Run performance test on Europe
        run: |
          echo "Running performance test on Europe:"
          railway run -s xmtp-qa-testing:europe yarn install
          railway run -s xmtp-qa-testing:europe yarn ts_performance > logs/europe-performance.log 2>&1
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      # Asia Region Test
      - name: Run performance test on Asia
        run: |
          echo "Running performance test on Asia:"
          railway run -s xmtp-qa-testing:asia yarn install
          railway run -s xmtp-qa-testing:asia yarn ts_performance > logs/asia-performance.log 2>&1
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Upload log files
        uses: actions/upload-artifact@v4
        with:
          name: performance-logs
          path: logs/

      - name: Print completion message
        run: echo "Railway test execution completed for all regions"
