name: Test Railway Integration

on:
  # Manual trigger only for testing
  workflow_dispatch:

jobs:
  test-railway:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Setup environment
        run: |
          echo "Setting up environment variables for Railway"
          # Create .env file with required variables
          touch .env
          echo "RAILWAY_SERVICE_ID=${{ secrets.RAILWAY_SERVICE_ID }}" >> .env
          echo "RAILWAY_API_TOKEN=${{ secrets.RAILWAY_API_TOKEN }}" >> .env
          echo "RAILWAY_PROJECT_TOKEN=${{ secrets.RAILWAY_PROJECT_TOKEN }}" >> .env
          echo "RAILWAY_PROJECT_ID=${{ secrets.RAILWAY_PROJECT_ID }}" >> .env
          echo "RAILWAY_ENVIRONMENT_ID=${{ secrets.RAILWAY_ENVIRONMENT_ID }}" >> .env

      - name: Run performance tests on Railway
        run: railway run --service xmtp-qa-testing:us-west yarn performance
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}

      - name: Print completion message
        run: echo "Railway test execution completed"
