name: Check Runner Location

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  check-location:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check Runner IP and Location
        run: |
          echo "=== RUNNER INFORMATION ==="
          echo "Runner name: $RUNNER_NAME"
          echo "Runner OS: $RUNNER_OS"
          echo "GitHub server URL: $GITHUB_SERVER_URL"

          echo -e "\n=== NETWORK INFORMATION ==="
          echo "IP Address: $(curl -s https://api.ipify.org)"
          echo "Hostname: $(hostname -f)"

          echo -e "\n=== LOCATION DETAILS ==="
          curl -s https://ipinfo.io | jq '.'

          echo -e "\n=== NETWORK ROUTE ==="
          traceroute -m 15 github.com

          echo -e "\n=== LATENCY TESTS ==="
          echo "Ping to github.com:"
          ping -c 5 github.com

          echo -e "\nPing to various regions:"
          echo "US East (N. Virginia):"
          ping -c 3 us-east-1.amazonaws.com || echo "Failed"
          echo "US West (Oregon):"
          ping -c 3 us-west-2.amazonaws.com || echo "Failed"
          echo "Europe (Ireland):"
          ping -c 3 eu-west-1.amazonaws.com || echo "Failed"
          echo "Asia Pacific (Tokyo):"
          ping -c 3 ap-northeast-1.amazonaws.com || echo "Failed"
