name: Package Compatibility Test

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # Run weekly on Sundays at midnight

jobs:
  test-package-compatibility:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 21, 22, 23]
        package-manager: [npm, yarn, pnpm, bun]
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: xmtp/xmtp-qa-testing
          path: xmtp-qa-testing

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        if: matrix.package-manager == 'pnpm'
        uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Install Bun
        if: matrix.package-manager == 'bun'
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Navigate to gm-bot directory
        run: cd xmtp-qa-testing/bots/gm-bot

      - name: Clean previous installations
        run: |
          cd xmtp-qa-testing/bots/gm-bot
          rm -rf node_modules
          rm -rf dist
          rm -rf .yarn
          rm -f package-lock.json
          rm -f yarn.lock
          rm -f pnpm-lock.yaml
          rm -f bun.lockb

      - name: Install dependencies with npm
        if: matrix.package-manager == 'npm'
        run: |
          cd xmtp-qa-testing/bots/gm-bot
          npm install

      - name: Install dependencies with yarn
        if: matrix.package-manager == 'yarn'
        run: |
          cd xmtp-qa-testing/bots/gm-bot
          touch yarn.lock
          yarn install

      - name: Install dependencies with pnpm
        if: matrix.package-manager == 'pnpm'
        run: |
          cd xmtp-qa-testing/bots/gm-bot
          pnpm install

      - name: Install dependencies with bun
        if: matrix.package-manager == 'bun'
        run: |
          cd xmtp-qa-testing/bots/gm-bot
          bun install

      - name: Build project
        run: |
          cd xmtp-qa-testing/bots/gm-bot
          ${{ matrix.package-manager }} run build

      - name: Set environment variables
        run: |
          cd xmtp-qa-testing/bots/gm-bot
          echo "XMTP_ENV=${{ vars.XMTP_ENV }}" > .env
          echo "WALLET_KEY=${{ secrets.WALLET_KEY }}" >> .env
          echo "ENCRYPTION_KEY=${{ secrets.ENCRYPTION_KEY }}" >> .env

      - name: Run client check
        run: |
          cd xmtp-qa-testing/bots/gm-bot
          ${{ matrix.package-manager }} run client-check
