name: TS_Delivery
description: "should verify message loss when receiving via 200 streams"

on:
  schedule:
    - cron: "*/40 * * * *" # every 40 min
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      LOGGING_LEVEL: ${{ vars.LOGGING_LEVEL }}
      XMTP_ENV: ${{ vars.XMTP_ENV }}
      GEOLOCATION: ${{ vars.GEOLOCATION }}
      DELIVERY_AMOUNT: ${{ vars.DELIVERY_AMOUNT }}
      DELIVERY_RECEIVERS: ${{ vars.DELIVERY_RECEIVERS }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "yarn"
        env:
          SKIP_YARN_COREPACK_CHECK: "1"
      - name: Ensure data folder exists
        run: mkdir -p .data
      - name: List data folder contents
        run: ls -la .data
      - run: corepack enable
      - run: yarn
      - name: Create logs directory
        run: mkdir -p logs
      - name: Run tests with retry
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 3
          command: |
            echo "Running TS_Delivery test:"
            # Run test and filter out sqlcipher_mem_lock error messages
            yarn test TS_Delivery 2>&1 | grep -v "sqlcipher_mem_lock: mlock" > logs/ts-delivery.log
            # Check the exit code of the test command (need to use pipestatus since we're using a pipe)
            TEST_EXIT_CODE=${PIPESTATUS[0]}
            if [ $TEST_EXIT_CODE -ne 0 ]; then
              echo "Test failed with exit code $TEST_EXIT_CODE"
              exit 1
            fi

            # Test passed, ignore unhandled errors
            echo "Test completed successfully"
          retry_on: error
      - name: Upload log files
        uses: actions/upload-artifact@v4
        with:
          name: delivery-logs
          path: logs/ts-delivery.log
