name: TS_Delivery
description: "should verify message loss when receiving via 200 streams"

on:
  schedule:
    # This will only run on the default branch (main)
    - cron: "*/40 * * * *" # every 40 min
  workflow_dispatch:
    # This allows manual triggering on any branch

jobs:
  check-branch:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Check if should run
        id: check
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" || "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "Should run tests"
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            echo "Skipping tests on non-main branch for scheduled events"
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi

  test:
    needs: check-branch
    if: ${{ needs.check-branch.outputs.should_run == 'true' }}
    runs-on: ubuntu-latest
    env:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      LOGGING_LEVEL: ${{ vars.LOGGING_LEVEL }}
      XMTP_ENV: ${{ vars.XMTP_ENV }}
      GEOLOCATION: ${{ vars.GEOLOCATION }}
      DELIVERY_AMOUNT: ${{ vars.DELIVERY_AMOUNT }}
      DELIVERY_RECEIVERS: ${{ vars.DELIVERY_RECEIVERS }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "yarn"
        env:
          SKIP_YARN_COREPACK_CHECK: "1"
      - name: Ensure data folder exists
        run: mkdir -p .data
      - name: Cache data folder and .env file
        uses: actions/cache@v3
        with:
          path: |
            .data
            .env
          key: ${{ runner.os }}-TS_Delivery-cache
          restore-keys: |
            ${{ runner.os }}-TS_Delivery-
          enableCrossOsArchive: false
          fail-on-cache-miss: false
      - run: corepack enable
      - run: yarn
      - name: Run tests
        run: yarn test TS_Delivery
