name: TS_Delivery
description: "should verify delivery of the library in the dev network"

on:
  schedule:
    - cron: "*/32 * * * *" # This cron expression means every 32 minutes
  workflow_dispatch:

jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Install dependencies once
        run: yarn install

      - name: Create logs directory
        run: mkdir -p logs

      # US East Region Test
      - name: Run delivery test on US East
        id: us-east-test
        continue-on-error: true
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: |
            echo "Running delivery test on US East:"
            railway run -s xmtp-qa-testing:us-east DELIVERY_AMOUNT=100 DELIVERY_RECEIVERS=45 yarn test ts_delivery | tee logs/us-east-delivery.log
            # Check the exit code of the test command
            TEST_EXIT_CODE=${PIPESTATUS[0]}
            if [ $TEST_EXIT_CODE -ne 0 ]; then
              echo "Test failed with exit code $TEST_EXIT_CODE"
              exit 1
            fi
          retry_on: error
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      - name: Upload log files
        uses: actions/upload-artifact@v4
        with:
          name: delivery-logs
          path: logs/

      - name: Check for failures
        run: |
          echo "Region test results:"
          echo "US East: ${{ steps.us-east-test.outcome }}"

          if [[ "${{ steps.us-east-test.outcome }}" == "failure" ]]; then
            echo "One or more region tests failed after retries"
            echo "See logs for details"
            exit 1  # Make the workflow fail if any region test failed
          fi

      - name: Print completion message
        run: echo "Railway test execution completed for all regions"
