name: TS_Geolocation
description: "should verify geolocation of the library in the dev network"

on:
  schedule:
    - cron: "*/32 * * * *" # This cron expression means every 32 minutes
  workflow_dispatch:

jobs:
  geolocation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Install dependencies once
        run: yarn install

      - name: Create logs directory
        run: mkdir -p logs

      # US West Region Test
      - name: Run performance test on US West
        id: us-west-test
        run: |
          for i in {1..3}; do
            echo "Attempt $i for US West region..."
            railway run -s xmtp-qa-testing:us-west yarn test ts_performance
            exit_code=$?
            if [ $exit_code -eq 0 ]; then
              echo "US West tests passed successfully!"
              break
            fi
            if [ $i -eq 3 ]; then
              echo "US West test failed after 3 attempts."
              exit 1
            fi
            echo "US West test failed with exit code $exit_code. Retrying..."
            sleep 10
          done
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      # US East Region Test
      - name: Run performance test on US East
        id: us-east-test
        run: |
          for i in {1..3}; do
            echo "Attempt $i for US East region..."
            railway run -s xmtp-qa-testing:us-east yarn test ts_performance
            exit_code=$?
            if [ $exit_code -eq 0 ]; then
              echo "US East tests passed successfully!"
              break
            fi
            if [ $i -eq 3 ]; then
              echo "US East test failed after 3 attempts."
              exit 1
            fi
            echo "US East test failed with exit code $exit_code. Retrying..."
            sleep 10
          done
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      # Europe Region Test
      - name: Run performance test on Europe
        id: europe-test
        run: |
          for i in {1..3}; do
            echo "Attempt $i for Europe region..."
            railway run -s xmtp-qa-testing:europe yarn test ts_performance
            exit_code=$?
            if [ $exit_code -eq 0 ]; then
              echo "Europe tests passed successfully!"
              break
            fi
            if [ $i -eq 3 ]; then
              echo "Europe test failed after 3 attempts."
              exit 1
            fi
            echo "Europe test failed with exit code $exit_code. Retrying..."
            sleep 10
          done
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      # Asia Region Test
      - name: Run performance test on Asia
        id: asia-test
        run: |
          for i in {1..3}; do
            echo "Attempt $i for Asia region..."
            railway run -s xmtp-qa-testing:asia yarn test ts_performance
            exit_code=$?
            if [ $exit_code -eq 0 ]; then
              echo "Asia tests passed successfully!"
              break
            fi
            if [ $i -eq 3 ]; then
              echo "Asia test failed after 3 attempts."
              exit 1
            fi
            echo "Asia test failed with exit code $exit_code. Retrying..."
            sleep 10
          done
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Upload log files
        uses: actions/upload-artifact@v4
        with:
          name: performance-logs
          path: logs/

      - name: Check for failures
        run: |
          echo "Region test results:"
          echo "US West: ${{ steps.us-west-test.outcome }}"
          echo "US East: ${{ steps.us-east-test.outcome }}"
          echo "Europe: ${{ steps.europe-test.outcome }}"
          echo "Asia: ${{ steps.asia-test.outcome }}"

          if [[ "${{ steps.us-west-test.outcome }}" == "failure" || "${{ steps.us-east-test.outcome }}" == "failure" || "${{ steps.europe-test.outcome }}" == "failure" || "${{ steps.asia-test.outcome }}" == "failure" ]]; then
            echo "One or more region tests failed after retries"
            exit 1  # Make the workflow fail if any region test failed
          fi

      - name: Print completion message
        run: echo "Railway test execution completed for all regions"
