name: TS_Gm
description: "should verify performance of the library in the dev network"

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    # Try without environment specification first to test repository-level secrets
    # environment: Dev
    env:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      LOGGING_LEVEL: ${{ vars.LOGGING_LEVEL }}
      XMTP_ENV: ${{ vars.XMTP_ENV }}
      GEOLOCATION: ${{ vars.GEOLOCATION }}
      GM_BOT_ADDRESS: ${{ vars.GM_BOT_ADDRESS }}
    steps:
      - uses: actions/checkout@v4
      - name: Debug API key
        run: |
          if [ -n "${{ secrets.DATADOG_API_KEY }}" ]; then
            echo "API key is available in test job"
          else
            echo "API key is NOT available in test job"
          fi
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "yarn"
        env:
          SKIP_YARN_COREPACK_CHECK: "1"
      - run: corepack enable
      - run: yarn

      - name: Run tests with retry
        id: run_tests
        run: |
          for i in {1..3}; do
            echo "Attempt $i..."
            if yarn test TS_Gm; then
              echo "Tests passed on attempt $i"
              echo "test_failed=false" >> $GITHUB_OUTPUT
              break
            fi
            if [ $i -eq 3 ]; then
              echo "Test failed after 3 attempts."
              echo "test_failed=true" >> $GITHUB_OUTPUT
              exit 1
            fi
            sleep 10
          done

  # Call the reusable Datadog reporting workflow
  report-to-datadog:
    needs: test
    if: always() # Run even if the test job fails
    # Try without environment specification
    # environment: Dev
    uses: ./.github/workflows/datadog-report.yml
    with:
      workflow_name: "TS_Gm"
      environment: "Dev"
      status: ${{ needs.test.result }}
    secrets:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
