name: TS_Gm
description: "should verify health of agents"

on:
  schedule:
    - cron: "10 * * * *" # Runs at 10 minutes past each hour
  workflow_dispatch:

  pull_request:
    branches:
      - main

jobs:
  TS_Gm:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [production]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "yarn"
        env:
          SKIP_YARN_COREPACK_CHECK: "1"
      - name: Enable corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn
      - name: Make test script executable
        run: chmod +x ./scripts/run-test.sh
      - name: Run tests with retry
        env:
          DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
          LOGGING_LEVEL: ${{ vars.LOGGING_LEVEL }}
          XMTP_ENV: ${{ matrix.environment }}
          GEOLOCATION: ${{ vars.GEOLOCATION }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: ./scripts/run-test.sh TS_Gm 1

      - name: Send Slack notification
        if: always()
        env:
          JOB_STATUS: ${{ job.status }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
        run: npx tsx helpers/slack.ts
      - name: Upload reports and snapshots artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ job.name }}_${{ matrix.environment }}
          path: |
            logs/
            logs/**/*.png
