name: TS_Gm_production
description: "should verify performance of the library in the production network"

on:
  schedule:
    - cron: "30 * * * *" # Runs at 30 minutes past each hour
  workflow_dispatch:

jobs:
 