name: TS_Geolocation
description: "should verify geolocation of the library in the dev network"

on:
  schedule:
    - cron: "*/32 * * * *" # This cron expression means every 32 minutes
  workflow_dispatch:

jobs:
  geolocation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Install dependencies once
        run: yarn install

      - name: Create logs directory
        run: mkdir -p logs

      # # US West Region Test
      # - name: Run performance test on US West
      #   id: us-west-test
      #   continue-on-error: true
      #   uses: nick-fields/retry@v2
      #   with:
      #     timeout_minutes: 10
      #     max_attempts: 3
      #     command: |
      #       echo "Running performance test on US West:"
      #       railway run -s xmtp-qa-testing:us-west yarn test ts_performance | tee logs/us-west-performance.log
      #       # Check the exit code of the test command
      #       TEST_EXIT_CODE=${PIPESTATUS[0]}
      #       if [ $TEST_EXIT_CODE -ne 0 ]; then
      #         echo "Test failed with exit code $TEST_EXIT_CODE"
      #         exit 1
      #       fi
      #     retry_on: error
      #   env:
      #     RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      # # US East Region Test
      # - name: Run performance test on US East
      #   id: us-east-test
      #   continue-on-error: true
      #   uses: nick-fields/retry@v2
      #   with:
      #     timeout_minutes: 10
      #     max_attempts: 3
      #     command: |
      #       echo "Running performance test on US East:"
      #       railway run -s xmtp-qa-testing:us-east yarn test ts_performance | tee logs/us-east-performance.log
      #       # Check the exit code of the test command
      #       TEST_EXIT_CODE=${PIPESTATUS[0]}
      #       if [ $TEST_EXIT_CODE -ne 0 ]; then
      #         echo "Test failed with exit code $TEST_EXIT_CODE"
      #         exit 1
      #       fi
      #     retry_on: error
      #   env:
      #     RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      # # Europe Region Test
      # - name: Run performance test on Europe
      #   id: europe-test
      #   continue-on-error: true
      #   uses: nick-fields/retry@v2
      #   with:
      #     timeout_minutes: 10
      #     max_attempts: 3
      #     command: |
      #       echo "Running performance test on Europe:"
      #       railway run -s xmtp-qa-testing:europe yarn test ts_performance | tee logs/europe-performance.log
      #       # Check the exit code of the test command
      #       TEST_EXIT_CODE=${PIPESTATUS[0]}
      #       if [ $TEST_EXIT_CODE -ne 0 ]; then
      #         echo "Test failed with exit code $TEST_EXIT_CODE"
      #         exit 1
      #       fi
      #     retry_on: error
      #   env:
      #     RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      # Asia Region Test
      - name: Run performance test on Asia
        id: asia-test
        continue-on-error: true
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: |
            echo "Running performance test on Asia:"
            railway run -s xmtp-qa-testing:asia yarn test ts_performance | tee logs/asia-performance.log
            # Check the exit code of the test command
            TEST_EXIT_CODE=${PIPESTATUS[0]}
            if [ $TEST_EXIT_CODE -ne 0 ]; then
              echo "Test failed with exit code $TEST_EXIT_CODE"
              exit 1
            fi
          retry_on: error
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Upload log files
        uses: actions/upload-artifact@v4
        with:
          name: performance-logs
          path: logs/

      - name: Check for failures
        run: |
          echo "Region test results:"
          echo "US West: ${{ steps.us-west-test.outcome }}"
          echo "US East: ${{ steps.us-east-test.outcome }}"
          echo "Europe: ${{ steps.europe-test.outcome }}"
          echo "Asia: ${{ steps.asia-test.outcome }}"

          if [[ "${{ steps.us-west-test.outcome }}" == "failure" || "${{ steps.us-east-test.outcome }}" == "failure" || "${{ steps.europe-test.outcome }}" == "failure" || "${{ steps.asia-test.outcome }}" == "failure" ]]; then
            echo "One or more region tests failed after retries"
            echo "See logs for details"
            exit 1  # Make the workflow fail if any region test failed
          fi

      - name: Print completion message
        run: echo "Railway test execution completed for all regions"
