name: TS_Geolocation
description: "should verify geolocation of the library in the dev network"

on:
  schedule:
    - cron: "15,45 * * * *" # Runs at 15 and 45 minutes past each hour
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, production]
        region: [us-west, us-east, europe, asia]
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      LOGGING_LEVEL: ${{ vars.LOGGING_LEVEL }}
      XMTP_ENV: ${{ matrix.environment }}
      BATCH_SIZE: ${{ vars.BATCH_SIZE }}
      MAX_GROUP_SIZE: ${{ vars.MAX_GROUP_SIZE }}
      GEOLOCATION: ${{ matrix.region }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "yarn"
        env:
          SKIP_YARN_COREPACK_CHECK: "1"

      - run: corepack enable
      - run: yarn install

      - name: Create logs directory
        run: mkdir -p logs

      - name: Make geolocation test script executable
        run: chmod +x ./scripts/run-test.sh

      - name: Run performance test on ${{ matrix.region }}
        id: region-test
        run: ./scripts/run-test.sh TS_Performance
        continue-on-error: true

      - name: Upload log files
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ts_geolocation_${{ matrix.environment }}_${{ matrix.region }}
          path: logs/

      - name: Check for failures
        run: |
          echo "Region test results for ${{ matrix.region }}:"
          echo "Status: ${{ steps.region-test.outcome }}"

          if [[ "${{ steps.region-test.outcome }}" == "failure" ]]; then
            echo "Region test failed after retries"
            exit 1
          fi

      - name: Print completion message
        if: always()
        run: echo "Railway test execution completed for ${{ matrix.region }} in ${{ matrix.environment }}"
