name: TS_Performance
description: "should verify performance of the library in the dev network"

on:
  pull_request:
    branches: [deploy]
  schedule:
    - cron: "*/30 * * * *" # Runs every 30 minutes
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, production]
    env:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      LOGGING_LEVEL: ${{ vars.LOGGING_LEVEL }}
      XMTP_ENV: ${{ matrix.environment }}
      GEOLOCATION: ${{ vars.GEOLOCATION }}
      BATCH_SIZE: ${{ vars.BATCH_SIZE }}
      MAX_GROUP_SIZE: ${{ vars.MAX_GROUP_SIZE }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "yarn"
        env:
          SKIP_YARN_COREPACK_CHECK: "1"
      - run: corepack enable
      - run: yarn
      - name: Make test script executable
        run: chmod +x ./scripts/run-test.sh
      - name: Run tests with retry
        id: test
        continue-on-error: true
        run: ./scripts/run-test.sh TS_Performance
      - name: Upload reports artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ts_performance_${{ matrix.environment }}
          path: logs/
      - name: Fail if tests failed
        if: steps.test.outcome == 'failure'
        run: exit 1
