name: TS_Performance
description: "should verify performance of the library in the dev network"

on:
  schedule:
    - cron: "0 0 * * *" # This cron expression means once a day at midnight UTC
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: Dev
    env:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "yarn"
        env:
          SKIP_YARN_COREPACK_CHECK: "1"
      - run: corepack enable
      - run: yarn
      - name: Run tests with retry
        run: |
          for i in {1..3}; do
            echo "Attempt $i..."
            yarn test TS_Performance && break
            if [ $i -eq 3 ]; then
              echo "Test failed after 3 attempts."
              exit 1
            fi
            sleep 10
          done
