name: TS_Streams
description: "should verify message loss when receiving via 200 streams"

on:
  schedule:
    - cron: "0 0 * * *" # This cron expression means once a day at midnight UTC
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: Dev
    env:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      LOGGING_LEVEL: ${{ vars.LOGGING_LEVEL }}
      XMTP_ENV: ${{ vars.XMTP_ENV }}
      GEOLOCATION: ${{ vars.GEOLOCATION }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "yarn"
        env:
          SKIP_YARN_COREPACK_CHECK: "1"
      - name: Ensure data folder exists
        run: mkdir -p .data
      - name: List data folder contents before caching
        run: ls -la .data
      - name: Cache data folder and .env file
        uses: actions/cache@v3
        with:
          path: |
            .data
            .env
          key: ${{ runner.os }}-TS_Streams-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-TS_Streams-
          enableCrossOsArchive: false
          fail-on-cache-miss: false
      - name: List data folder contents after cache restore
        run: ls -la .data
      - name: Count specific folders in .data directory
        run: |
          COUNT=$(find .data -type d -name "${{ runner.os }}-${{ github.run_id }}-testname-*" | wc -l)
          echo "Found $COUNT folders matching pattern: ${{ runner.os }}-${{ github.run_id }}-testname-*"
      - run: corepack enable
      - run: yarn
      - name: Run tests with retry
        run: |
          for i in {1..3}; do
            echo "Attempt $i..."
            yarn test TS_Streams && break
            if [ $i -eq 3 ]; then
              echo "Test failed after 3 attempts."
              exit 1
            fi
            sleep 10
          done
