name: Validate functional tests

on:
  push:
    branches-ignore: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "yarn"
        env:
          SKIP_YARN_COREPACK_CHECK: "1"
      - name: Enable corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn
      - name: Start dev environment
        run: ./dev/up
      - name: Sleep for 5 seconds
        run: sleep 5s
      # - name: Updating local generated inboxes
      #   run: yarn script local-update
      # - name: Sleep for 5 seconds
      #   run: sleep 5s
      - name: Run functional tests
        env:
          XMTP_ENV: local
          RUST_BACKTRACE: 1
          # Set this to true to help with debugging in GitHub Actions
          GITHUB_ACTIONS: true
          LOGGING_LEVEL: "off"
        run: yarn test groups
      - name: Upload reports artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: functional_test_logs
          path: logs/
